modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "null"

[[mods]]
modId = "foc"
version = "${version}"
displayName = "Forge of Creation"
authors = ""
description = ''
logoFile = "icon.png"

[[dependencies.foc]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.foc]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.foc]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"